config/routes.rb
Rails.application.routes.draw do
  root 'sessions#show'
  get '/login', to: 'sessions#show'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/verify_2fa', to: 'sessions#verify_2fa', as: 'verify_2fa'
  get '/verify', to: 'sessions#verify_index'

  get '/not_authorized', to: 'users#not_authorized', as: 'not_authorized'
  get '/dashboard', to: 'users#dashboard', as: 'dashboard'

  # Users routes
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
    validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: URI::MailTo::EMAIL_REGEXP }, 
                    uniqueness: { case_sensitive: false }
    def generate_two_factor_token
        update(two_factor_token: rand(10000..99999), two_factor_token_sent_at: Time.zone.now)
    end
    def send_two_factor_authentication_email
    UserMailer.verify(self,self.two_factor_token).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    check_session
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      if user.two_factor_enabled?
        user.generate_two_factor_token
        user.send_two_factor_authentication_email
        session[:user_mail] = params[:email]
        redirect_to verify_path
      else
        log_in user
        redirect_to root_path
      end
    else
      flash.now[:error] = "Incorrect email or password"
      render 'show'
    end
  end

  def verify_index
    redirect_to not_authorized_path unless session[:user_mail]
  end

  def verify_2fa
    if session[:user_mail]
      user = User.find_by_email(session[:user_mail])

      if user.two_factor_token == params['token']
        session[:user_id] = user.id
        session[:two_fa_login] = true
        print('inside 2fa')
        redirect_to dashboard_path
      else
        print('invalid token')
      end
    else
      redirect_to not_authorized_path
    end
  end

  def destroy
    log_out if session[:user_id]
    print('check session')
    print(session['user_id'])
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if session[:user_id]
      redirect_to dashboard_path
    else
    @user = User.new
    end
  end
  def not_authorized
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def dashboard
    if session[:user_id]
      @user = User.find(session[:user_id])
      else
        redirect_to not_authorized_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def log_out
      session.delete(:user_id)   
      session.delete(:user_mail)   
   end
   
   def check_session
    if session[:user_id]
      redirect_to dashboard_path
    end
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InnovalabsAuthTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
       <% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/dashboard.html.erb
        <div class="max-w-sm mx-auto bg-white rounded-lg overflow-hidden shadow-lg">
            <div class="border-b px-4 pb-6">
                <div class="text-center my-4">
                    <img class="h-32 w-32 rounded-full border-4 border-white mx-auto my-4" src="https://randomuser.me/api/portraits/women/21.jpg" alt="">
                    <div class="py-2">
                        <h3 class="font-bold text-2xl mb-1"><%=@user.name%></h3>
                        <div class="inline-flex text-gray-700 items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at" viewBox="0 0 16 16">
  <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z"/>
  <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648Zm-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
</svg>
                            <%=@user.email%>
                        </div>
                    </div>
                </div>
                <div class="flex gap-2 px-2">
                <%=button_to "Logout", logout_path,class:"flex-1 rounded-full bg-red-600 text-white antialiased font-bold hover:bg-blue-800 px-4 py-2", method: :delete%>
                </div>
            </div>
           
            </div>
        </div>

app/views/users/new.html.erb
<section class="h-screen">
  <div class="h-full">
    <!-- Left column container with background-->
    <div
      class="g-6 flex h-full flex-wrap items-center justify-center lg:justify-between">
      <div
        class="shrink-1 mb-12 grow-0 basis-auto md:mb-0 md:w-9/12 md:shrink-0 lg:w-6/12 xl:w-6/12">
        <img
          src="https://tecdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="w-full"
          alt="Sample image" />
      </div>
      <!-- Right column container -->
      <div class="mb-12 md:mb-0 md:w-8/12 lg:w-5/12 xl:w-5/12">
  <%= form_with(model: @user, url: '/users', class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4') do |f| %>
      <% if @user.errors.any? %>
      <div class="mb-4 bg-red-100 text-red-700 border border-red-400 rounded p-4">
        <p class="font-bold mb-2">Oops! Something went wrong.</p>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
          <!--Sign in section-->
          <!-- Email input -->


         <div class="relative mb-6" data-te-input-wrapper-init>
           
             <%= f.text_field :name, class: "peer block min-h-[auto] w-full rounded border-0 bg-transparent px-3 py-[0.32rem] leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" %>
               <%= f.label :name, class: "pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[2.15] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[1.15rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[1.15rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary peer-focus:bg-white" %>
          </div>
          <!-- Password input -->
          <div class="relative mb-6" data-te-input-wrapper-init>
            
             <%= f.email_field :email, class: "peer block min-h-[auto] w-full rounded border-0 bg-transparent px-3 py-[0.32rem] leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" %>
              <%= f.label :email, class: "pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[2.15] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[1.15rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[1.15rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary peer-focus:bg-white" %>
          </div>
          <div class="relative mb-6" data-te-input-wrapper-init>
   
             <%= f.password_field :password, class: "peer block min-h-[auto] w-full rounded border-0 bg-transparent px-3 py-[0.32rem] leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" %>
                       <%= f.label :password, class: "pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[2.15] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[1.15rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[1.15rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary peer-focus:bg-white" %>
          </div>
           <div class="relative mb-6" data-te-input-wrapper-init>
            
             <%= f.password_field :password_confirmation, class: "peer block min-h-[auto] w-full rounded border-0 bg-transparent px-3 py-[0.32rem] leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0 " %>
              <%= f.label :password_confirmation, class: "pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[2.15] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[1.15rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[1.15rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary peer-focus:bg-white" %>
          </div>
          <!-- Login button -->
          <div class="text-center lg:text-left">
            <%= f.submit 'Signup', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>

            <!-- Register link -->
            <p class="mb-0 mt-2 pt-1 text-sm font-semibold">
              Don't have an account?
             <%= link_to "Login", login_path,class: "text-red-400 hover:text-red-700" %>

            </p>
          </div>
    <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/not_authorized.html.erb
<div class="w3-display-middle">
<h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
<hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
<h3 class="w3-center w3-animate-right">You dont have permission to view this site.</h3>
<h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
<h6 class="w3-center w3-animate-zoom">error code:403 forbidden</h6>
</div>